synonymdev/react-native-ldk

- example/ios/Podfile.lock
- example/ldk/index.ts
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
This PR:
Adds timestamp information to the LDK account storage and is updated every time the storage is updated. A check has been added to importAccount to ensure the user does not successfully import an old or stale backup unless specifically instructed to overwrite the existing data.
- Adds timestamp to ELdkData, TLdkData & DefaultLdkDataShape in types.ts.
- Adds this.updateStorage to LightningManager class in lightning-manager.ts.
- Adds timestamp condition to importAccount method in lightning-manager.ts.
- Replaces this.setItem with this.updateStorage as needed throughout lightning-manager.ts.
- Creates updateTimestamp method in lightning-manager.ts.
- Creates parseData method in helpers.ts and implemented it as needed in lightning-manager.ts.
- Changes ldk.addPeer to lm.addPeer in …
> Add Timestamp To Storage Data

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
New ldk method:
``` javascript
const spendRes = await ldk.spendOutputs({
descriptorsSerialized: [abc123...],
outputs: [], //Shouldn't need to specify this if we're sweeping all funds to dest script
change_destination_script: 'a91407694cfd2bd43f4e0fe285a4d013456cb58d7eab87',
feerate_sat_per_1000_weight: 1000, 
});
```
`descriptorsSerialized` is an array of serialized descriptors received from `channel_manager_spendable_outputs` event.
`spendRes.value` is a hex encoded tx that needs to be broadcasted.
`feerate_sat_per_1000_weight` can maybe be changed to an enum if more convenient ('high' | 'normal' | 'low')
> Swift/Kotlin exposes keysManager.spend_spendable_outputs

- example/App.tsx
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/src/ldk.ts
- ldk.onEvent(...) will now return the `EmitterSubscription` and this can be used to unsubscribe at a later stage such as a useEffect cleanup when a component is unmounted.
- Removed old log subscription logic as it can be done with the above.
``` javascript
const sub = ldk.onEvent(EEventTypes.ldk_log, (log) => console.log(log));
//Done with subscription
sub.remove();
```
> Events unsubscribe

- example/App.tsx
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/utils/types.ts
- iOS and Android can create invoices with an unspecified amount
- iOS and Android can pay invoices while specifying amounts from sender
Create an invoice without passing `amountSats`
``` javascript
const createPaymentRequest = await ldk.createPaymentRequest({
description: 'paymeplz',
expiryDeltaSeconds: 999999,
});
```
Pay invoice with own amount if `amount_satoshis` is null
``` javascript
const decode = await ldk.decode({ paymentRequest });
if (!decode.amount_satoshis) {
//Missing amount so we can specify our own
const pay = await ldk.pay({
paymentRequest,
amountSats: 1234
});
}
```
> Zero sat invoice support

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/ios/Helpers.swift
- lib/src/ldk.ts
- lib/src/utils/result.ts
- lib/src/utils/types.ts
- Decoded invoice now expose `route_hints`
- Result type has `code` param that is returned by the native code when rejecting. (Will add this to separate result lib when I replace it in this project)
- If ldk.pay() fails with `invoice_payment_fail_routing` then checks are done to better explain the likely reasons for the failed payment.
- - If invoice contained route hints. Related to [this issue](https://github.com/lightningnetwork/lnd/issues/6870). (some newer versions of LND can cause channels with LDK to not be updated so LDK won't include hints)
- - If the node we're trying to pay is in our network graph.
- - If usable channels have enough outgoing capacity to route that amount.
> Route failed debugging

- lib/package.json
@coreyphillips thanks for your work on this module. I'm currently testing it and tried installing the npm package in a react-native `0.69.5` app and had to install using `npm i --force` since my peer dependency `react` was at `18.0.0`. This PR should fix that. Thanks :)
> Support newer react-native versions

- example/App.tsx
- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Exposes claimable balances which is an array of balances that includes `claimable_amount_satoshis` and the balance's `confirmation_height`/ `claimable_height`. Possible to include/exclude current open channels so it can just be used to show user's their pending and not yet spendable on chain balance.
- Fixed invalid `funding_txo`. Also now renamed to `funding_txid` to be more clear.
- `amountSats` unit fix for code clarity. Converting to milli sats in native code instead of JS.
- Adding network to backup data structure.
> Claimable balances and misc fixes

- example/App.tsx
- example/ios/Podfile.lock
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
This PR:
- Adds `payWithTimeout` helper method to `lightning-manager.ts` to properly subscribe to and listen for outgoing payment events.
- Updates example app accordingly.
> Subscribe To & Timeout Payments

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
iOS rapid gossip sync.
Note: incremental updates temporally disabled due to this [LDK issue](https://github.com/lightningdevkit/rust-lightning/issues/1784). Right now if a network graph is older than 24h we download a rapid gossip sync file from scratch (~5mb) but once patched these few lines can be removed to enable updates without downloading graph once a day.
> iOS rapid gossip sync

- example/ios/Podfile.lock
- example/ldk/index.ts
- example/package.json
- example/yarn.lock
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
This PR:
- Adds `getTransactionPosition` to `lm.start`.
- Corrects invalid `setConfirmedTx` params.
- We're now grabbing the relevant position of the tx in the block and passing that to `setConfirmedTx`'s `txData` object instead of the output's index.
- We are now passing the full tx to the `txData` object.
- Bumps version to `0.0.72`.
> fix(lightning): Add getTransactionPosition

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- `ldkListChannelFiles()` Returns all channel monitor file names.
- Backup all channel monitors instead of just current channels. Safer to back up everything in case there are still unclaimed funds from previously closed channels.
- Backups now work without starting LDK.
> Backup all past channels

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- lib/ios/Ldk.swift
- Android rapid gossip sync
- Android limit graph queries to avoid memory limit crashes in RN
- There's [this issue](https://github.com/lightningdevkit/rust-lightning/issues/1784) in LDK causing some rapid gossip syncing to fail. It's been fixed but waiting on 0.0.113 to test. For now the graph will sync from scratch (downloading 5mb) every 24 hours.
> Android rapid gossip sync

- lib/ios/Helpers.swift
- lib/src/ldk.ts
- lib/src/utils/helpers.ts
- Returns correct invoice description instead of null
- Removes `lightning:` from invoices. At a later stage we can add bip21 support so anyone using using this doesn't have to worry about parsing multiple formats first when decoding lightning invoices.
> iOS fixed invoice description

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkLogger.kt
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Helpers.swift
- lib/ios/Ldk.swift
- iOS and Android persisting scorer
- Removes rapid gossip sync hack preventing incremental updates to graph
- Only resolves promise once graph sync is complete to ensure the graph is ready when starting the node so the invoice payer has latest updates.
- Temporary hack that deletes the graph so it syncs from scratch on next load if it gets a `LightningError`. I believe this is caused by switching RGS servers or restarting the server.
> Remove RGS hacks

- lib/android/gradle.properties
This PR:
- Bumps `Ldk_kotlinVersion` to `1.5.20` in `gradle.properties`.
> Bump Kotlin Version

- example/ios/Podfile.lock
- example/utils/constants.ts
- lib/package.json
- lib/src/lightning-manager.ts
- Fixes the incorrect fee rate when claiming a spendable output from a channel close (Any currently stuck outputs should be spent again with corrected fee rate)
- Reverts example app constants accidentally changed in previous PR
> Stuck output fix

- example/App.tsx
- example/package.json
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
- Caches all outputs before creating spending tx
- Recovery function that attempts to re spend all cached outputs and then reconstruct outputs not cached in previous versions based on cached transactions that failed to broadcast due to low fee bug
- Improved logging
- Pay with timeout of 60s instead of 3 attempts
> Spend stuck outputs

- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/package.json
- Reverse outpoint tx ID when spending stuck outputs
- Version bump
> Android reconstructAndSpendOutputs endianness fix

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Passes hard timeout to bindings so payments are given up at the same time as the JS times outs. This fixes an issue where people were having successful payments and the UI would say it was a failure and never add it to the tx list.
- When subscribing to outgoing payment events only resolve with an error if `payment_failed_permanently` is `true` As to not prematurely abandon payments that can be auto retried. This fixes an issue where first attempts at paying an invoice failed but manually retrying worked.
> Fixes failed first payments

- README.md
- lib/src/index.ts
- lib/src/mock.ts
- add mock that can be used in enviroments, like jest, were you can't use RN.
- ldk can now be directly imported from root package, this help making mocking easy
> feat: add jest mock

- example/ios/Podfile.lock
- lib/package.json
This PR:
- Bumps `react-native-ldk` version to `0.0.96`.
> Bump version to 0.0.96

- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/package.json
If LDK is stopped and started again on Android it throws an error when trying to set the storage path again. This check was previously removed from Swift but not Kotlin.
> Android allow accountStoragePath to be set again

- example/App.tsx
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
Links to issue [114](https://github.com/synonymdev/react-native-ldk/issues/114)
This PR adds claimed payments to storage in `{baseStoragePath}/payments_claimed.json` 
Would like feedback on if the strategy for storing transactions is correct. Could possibly be a parameter to `lm.start()` where it could be a read/write interface for developers to choose a storage strategy.
> feat: Add payments claimed to storage

- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Helpers.swift
Temporary removed probabilistic scorer caching causing crash on iOS
> iOS remove cached scorer

- example/App.tsx
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Classes/LdkLogger.swift
- lib/ios/Helpers.swift
- lib/ios/Ldk.swift
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Changes claimed transactions to be written native in swift/kotlin as we often get missed react native events which results in the transactions happening but never being recorded in Bitkit. 
- Added sent payments persistence.
- Records pending and failed payments for claimed/sent. When an tx callback occurs those entries are updated with the correct state. This way users can see an incoming/outgoing payment in their activity list.
> Native transaction persistence

- example/utils/helpers.ts
- lib/src/lightning-manager.ts
- lib/src/mock.ts
- lib/src/utils/helpers.ts
- lib/src/utils/networks.ts
- lib/src/utils/types.ts
This PR:
- Creates `networks.ts` file and adds `signet` key with new params.
- Updates references to the `networks` file accordingly.
- Updated `ENetworks.mainnet` value to `bitcoin` to match bitcoinjs-lib's `networks` object key.
> feat(lightning): Add signet params to networks object

- example/App.tsx
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Saving invoices to disk
- Lookup and decode invoice by payment hash
- Optionally backup tx history (I suspect backups are getting larger and failing more)
Closes https://github.com/synonymdev/react-native-ldk/issues/152
Closes https://github.com/synonymdev/react-native-ldk/issues/153
> Store invoices

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkFeeEstimator.kt
- lib/ios/Classes/LdkFeeEstimator.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
Fixes a bug where we were passing `normal` fee as the `mempoolMinimum` fee
> fix: new fee type (mempoolMinimum)

- example/ios/Podfile.lock
- example/tests/lnd.ts
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
This PR:
- Prevents `syncLdk` from having overlapping calls.
- If a sync is underway it will return the outcome of the current sync unless `force` is set to `true`. If `force` is set to `true` it will perform another sync once the current is complete.
- Adds timeouts to network queries in `syncLdk`.
- Adds retry attempts to `syncLdk` if a network query times out.
> fix(lightning): syncLdk Updates

- backup-server/src/storage.js
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/BackupClient.kt
- lib/ios/Classes/BackupClient.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/utils/types.ts
- Refactors BackupClient in Swift and Kotlin so listFiles is it's own method
- Exposes listFiles to RN so backup state can be checked before starting a restore
- Server bug fix to prevent list files function from returning files in sub directories
> feat: list files backed up

- example/Dev.tsx
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- Refactors claimable balance result into a reusable function `getClaimableBalancesAsJson()` in Swift and Kotlin
- Dumps node state to log file on startup and each sync for debugging. 
- Node ID
- Open channel details
- All claimable balances
- RGS last sync time
- Connected peers
- Storage
- Backup status
> feat: dump useful node info to logs on startup and each sync

- example/Dev.tsx
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.swift
- lib/ios/LightningDevKit.xcframework/ios-arm64/LightningDevKit.framework/Headers/ldk_ver.h
- lib/ios/LightningDevKit.xcframework/ios-arm64_x86_64-simulator/LightningDevKit.framework/Headers/ldk_ver.h
- lib/ios/LightningDevKit.xcframework/ios-arm64_x86_64-simulator/LightningDevKit.framework/_CodeSignature/CodeResources
- lib/package.json
- lib/src/lightning-manager.ts
- Fixes a bug where only regtest or the last network to be started up was used when restoring. Devs now need to specify the network they wish to restore. Also spins up new keys manager just to ensure backups are setup with the current seed.
- Updates LDK bindings to use official [0.0.117 release ](https://github.com/lightningdevkit/ldk-swift/releases/tag/0.0.117)
> Specify network when restoring from remote backup

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- Downloads RGS file and updates on background thread then performs callback on main thread
- Removes auto channel close on failed remote persist. It was removed from iOS a while back but stayed in Android.
> fix: android perform rgs download and update on background thread

- lib/src/lightning-manager.ts
This PR:
- Prevents simultaneous calls to lm.start.
- Will allow for multiple calls if a new account name is passed to the `lm.start` method.
- Adds `isStarting`, `pendingStartPromises` & `previousAccountName` to `lightning-manager.ts`.
- Adds `resolveAllPendingStartPromises` & `handleStartError` to `lightning-manager.ts`.
- Updates `start` method  in `lightning-manager.ts`  accordingly.
> fix(lightning): Limit lm.start Calls

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/BackupClient.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- lib/ios/Classes/BackupClient.swift
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Classes/LdkPersist.swift
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- Removes initChainMonitor() call. Chain monitor is just now initialised when constructing the channel manager where it is needed. Might improve a restart bug on iOS.
- Android and iOS auto retry on remote persist fail. This is a temporary solution to avoid crashes and random force closes.
> Remote persist retries

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/ios/Helpers.swift
- lib/package.json
- lib/src/utils/types.ts
short_channel_id, inbound_scid_alias and inbound_payment_scid are all UInt64 types which overflow in JS numbers so converted number types to strings
> fix: int overflow for short channel IDs

- example/Dev.tsx
- example/ldk/index.ts
- example/tests/lnd.ts
- example/tests/unit.ts
- example/utils/helpers.ts
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Android and iOS download a pre-populated scorer from RGS server to improve payment reliability.
- Removed old backup function calls from example app.
- Added deprecated warnings to old backup calls, will remove completely in a future PR to simplify the code.
- Startup speed improvements:
- Grouped startup functions that are not required to be run in any order to run async.
- Skip startup param check `skipParamCheck: true` in lm.start(). Can be left on default false for debugging but should be used to avoid additional network calls on each startup once in prod. 
- addPeers and sync methods called without await at the end of startup.
> feat: pre-populated scorer download

- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.swift
- lib/package.json
Gets more successful routing for shorter route payments setting base penalty as 500 sats.
Will come back and allow the whole score params object to be set from the JS side.
> fix: increasing base_penalty_msat

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/BackupClient.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- lib/ios/Classes/BackupClient.swift
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Classes/LdkPersist.swift
- lib/ios/Ldk.swift
Remote state persistence now happens in the background. This fixes crashes on iOS when moving app to background during persisting. Also should improve android performance.
- iOS performs backups on 3 dispatch queues. One for channel manager, channel monitors and misc. This ensures each backup is done in the correct order without grouped older ones ever completing before a newer persist so server always has the latest state.
- Android uses background threads, a backup queue and a locking mechanism to achieve the same thing.
> Async backups

- backup-server/.npmrc
- backup-server/package.json
- example/Dev.tsx
- example/ios/Podfile.lock
- example/ldk/index.ts
- example/utils/helpers.ts
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/CustomKeysManager.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Classes/CustomKeysManager.swift
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
Outputs from channel closes now get spent directly to on chain wallet.
- Extends the default LDK keys manager so we can provide our own signer provider and overrides functions that return destination script and shutdown script pubkey.
- Existing sweeping logic is kept for channels opened prior to this update. Going forward as a new channel is opened the channel ID is appended to a file so when it comes time to sweep outputs from a channel close it will skip this sweeping step if the channel ID is found as the channel was opened with new adapted keys manager.
- `getAddress()` in JS needs to be adapted to return witness program and program version. Example app shows how.
> Custom keys manager

- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
Fixes the bitkit issue: 
- https://github.com/synonymdev/bitkit/issues/1494
For testing:
- Use the repro steps from the bitkit issue
Note:
On iOS this is already patched with the same logic, defaulting to `0` if the cast doesn't succeed.
> Fix: crash preventing user to ever recover wallet on Android

- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- lib/ios/Classes/LdkPersist.swift
- lib/package.json
- lib/src/lightning-manager.ts
- safely catch disk write fails. LDK will retry.
- version bump
> fix: ios and android catch channel write fails

- backup-server/src/server.js
- example/Dev.tsx
- example/ios/Podfile.lock
- example/ldk/index.ts
- example/tests/lnd.ts
- example/tests/utils/test-profile.ts
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/BackupClient.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkPersister.kt
- lib/ios/Classes/BackupClient.swift
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Classes/LdkPersist.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Allows for backing up and retrieving other non LDK related files
- Cleans up old event based backup logic but still keeps import function to allow older backups to be restore
- Removes backup setup outside of lm.start so apps need to call this first. Makes it more flexible as it can be used without starting LDK.
- Fixes a crash that happens when app is used without remote backups
> feat: allow for backing up any file to remote backup server

- example/Dev.tsx
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/BackupClient.kt
- lib/ios/Classes/BackupClient.swift
- lib/ios/Ldk.swift
- lib/src/utils/types.ts
New RN event for monitoring backup client state. 
Optional failure fields are included for temporary soft fails, BackupClient will continue to retry on it's own.
``` typescript
ldk.onEvent(EEventTypes.backup_state_update, (res: TBackupStateUpdate) => {
//file: {
//   lastQueued: number;
//   lastPersisted?: number;
//   lastFailed?: number;
//   lastErrorMessage?: string;
//}
}
```
> feat: ios backup client state event

- .github/workflows/mocha-anrdoid.sh
- .github/workflows/mocha-ios.yml
- backup-server/Dockerfile
- backup-server/package-lock.json
- backup-server/package.json
- example/Tests.tsx
- example/docker/docker-compose.yml
- example/e2e/ldk.test.js
- example/ldk/index.ts
- example/package.json
- example/tests/clightning.ts
- example/tests/eclair.ts
- example/tests/lnd.ts
- example/tests/unit.ts
- example/tests/utils/index.ts
- example/tests/utils/test-profile.ts
- example/yarn.lock
Looks like rn-ldk tried to add local peer before starting up.
Because it is unreachable during e2e tests, I'm increasing timeouts
> fix: increase timeout for e2e tests

- backup-server/package-lock.json
- backup-server/package.json
- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/utils/types.ts
Resolves #156 
- Saves invoice string when paying for a `bolt11` invoice to **sent** payments file
On Android also:
- Returns route hops info in case of `PaymentPathSuccessful` event (already exists in iOS)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206525067124277
> feat: add bolt11 invoice string to sent stored payments

- backup-server/package.json
- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/package.json
Resolves #211
- Returns a readable `reason` string for the `channel_manager_channel_closed` event:
```js
LOG  onChannelManagerChannelClosed: 
{"reason":"CooperativeClosure","channel_id":"…","user_channel_id":"b08az1306…"}
```
- Fixes `user_channel_id` on Android
> fix: channel closed event data

- lib/ios/Classes/LdkLogger.swift
Hi, after trying multiple times to make this app to build using EAS Build from expo, it always seems to fail at this step, but changing this line makes it work, am I missing something here or it really should be imported from LDKdevkit
This is the error that it returns
> use logger from ldkdevkit

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.swift
- lib/src/utils/types.ts
Resolves #220 
Add the invoice description to sent payments persistence, to have it readily available and remove the need of an additional `decode` call from the RN code.
See this `todo` line for more info on the reason:
https://github.com/synonymdev/bitkit/pull/1592/files#diff-d692e78fc8af95524590b3741723f8e0157016777629bdd768fc753b83daa30fR339
Tested with:
1. LND create invoice with description
```
lncli addinvoice --amt 2 --memo "test description 2"
```
Copy `payment_request`
2. Example app: `Pay Invoice` (should paste from clipboard)
3. Example app: `Get sent payments` : should print description ✅ 
| <img width="315" src="https://github.com/synonymdev/react-native-ldk/assets/4588074/1796bf84-27ce-4272-a578-fb88a65993ab"> |
| - |
> feat: Persist invoice payment description

- backup-server/src/server.js
- example/ios/Podfile.lock
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
This PR:
- Adds and tracks `confirmedWatchOutputs` in `lightning-manager.ts`.
- Increases timeout to `20000`ms.
- Updates `retrySyncOrReturnError` to return immediately if a `time-out` is detected.
- Replaces map with for of loop for Electrum queries.
- Adds `saveConfirmedWatchOutput` & `getConfirmedWatchOutputs` methods.
- Bumps version to `0.0.134`.
- Addresses #221
> Fix watchOutputs Loop

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
Helper function for getting any spendable outputs from force closed channels and trying to spend them again in the event they were not spent automatically.
> Retry spending outputs after force close

- example/ios/Podfile.lock
- example/rn-setup.js
- example/utils/helpers.ts
- example/utils/types.ts
- Changes example app to derive seed from mnemonic in way that is compatible with ldk-node. 
- Saves mnemonic to keychain instead and derives LDK seed when needed. (May have to create a new wallet if updating from an existing example app that only saved the seed and not the mnemonic.)
- Flipper currently broken, temporarily removing it.
> Derive LDK seed from mnemonic in example app

- example/Dev.tsx
- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/utils/types.ts
Lists all or just closed channel monitors. Can be used to read which claimable balances are coming from which channels.
> feat: list all channel monitors

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
- lib/ios/Classes/LdkChannelManagerPersister.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
Prevents duplicate payments from being received and overwriting the original received amount
> Duplicate payment receive fix

- example/ios/Podfile.lock
- example/yarn.lock
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- lib/yarn.lock
This PR:
- Updates `checkWatchOutputs` to verify the output index when sweeping a force closed channel by checking the output addresses against previously generated/retrieved addresses.
- Adds `@synonymdev/raw-transaction-decoder` as a dependency.
- Creates `saveAddressToFile` method and implements it in the `getAddress` method.
- Creates `readAddressesFromFile` method and implements is accordingly.
- Adds `addresses` to `LightningManager` class.
> Verify Watch Output Index

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Helpers.swift
- lib/src/lightning-manager.ts
- lib/src/utils/helpers.ts
- lib/src/utils/types.ts
- On startup (without holding up the startup function) iterate through all the stored broadcasted txs and remove any txs confirmed with 6+ blocks so we don't waste time rebroadcasting confirmed txs.
- Confirmed broadcasted txs are saved in a separate file as a backup.
- Fix iOS type for `inbound_payment_scid`
- Reverse txid for node state dump on Android
> Broadcasted transactions cleanup

- lib/src/lightning-manager.ts
Appends all closed channel monitor details to LSP log event body
```
{
"channelClose": {
"commitment_tx_fee": 2,
"pending_htlcs_count": 1,
"commitment_tx": "Data(channelClose.getCommitmentTx()).hexEncodedString()"
},
"channelFiles": [
{
"channel_id": "731a159d8829c8a233e421340dbe89985f19668098b82a0c58560aa8321de38c",
"counterparty_node_id": "0341e41583ad691951634e24dd20252d13feace9286a85d47f220dde74e7e09a15",
"funding_txo_index": 0,
"funding_txo_txid": "8ce31d32a80a56580c2ab8988066195f9889be0d3421e433a2c829889d151a73",
"claimable_balances": [
{
"amount_satoshis": 50000,
"type": "ClaimableAwaitingConfirmations",
"confirmation_height": 6759
}
]
}
]
}
```
> feat: append channel monitor details to lsp log

- example/ios/Podfile.lock
- example/yarn.lock
- lib/package.json
- lib/yarn.lock
This PR:
- Upgrades `@synonymdev/raw-transaction-decoder` to `1.1.0` to include the following:
- https://github.com/synonymdev/raw-transaction-decoder/pull/1
> Upgrades raw-transaction-decoder to 1.1.0

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/package.json
- Increases timeout when connecting dropped peers to 3 seconds
- Adds all peers whether initial connection was success or failure to the watch list
> fix: increase android connect timeout to 3s

- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.swift
- iOS only restart LDK if app was in background for +5 seconds. Prevents unintentionally restarts.
- iOS timer to watch for dropped peer connections.
- iOS check for preventing additional connections when a peer is already connecting or connecting.
> feat: ios restart debounce, dropped peer connection handler

- .github/workflows/e2e-android.yml
- example/ios/Podfile.lock
- example/ios/exmpl.xcodeproj/project.pbxproj
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/CustomKeysManager.kt
- lib/ios/Classes/CustomKeysManager.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/package.json
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
Previously we were persisting every new close address to file. This resulted in saving many addresses that may have not been used for a channel close.
Rather persist addresses:
- When confirmed to be used for shutdown script when accepting a channel (for coop closes)
- When sweeping outputs (from a force close).
This way Bitkit can use this address file to explicitly watch for any new txs and update the UI after a coop or force close.
> fix: save addresses only when used for closing a channel

- backup-server/src/server.js
- lib/package.json
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Remote backup for persisted peers
- Accepts address backups on server
> fix: backup persisted peers

- example/ldk/index.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
- Removed `trustedZeroConfPeers` from startup params
- `lm.setTrustedZeroConfPeerNodeIds(nodeIds)` can be used at any point in the app life cycle to update and persist the current list of trusted zero conf peers.
> feat: persist trusted peers to disk

- README.md
- backup-server/package.json
- example/ios/Podfile.lock
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/package.json
Fixes synonymdev/bitkit#2133
(Android-only) Fix to avoid `ConcurrentModificationException` while `addedPeers` list is modified from other thread.
Former setup:
1. Scheduling was done using `TimerTask` which creates a different thread each time it's invoked
2. Since we also change `addedPeers` from react-native, there was a chance to get into this issue especially at app start, when both the react-native code as well as the native LDKModule code would mutate the same list.
Fix:
Use a thread-safe mutable list implementation, I picked `ConcurrentLinkedQueue` because it's less resource-consuming than other options.
Extra:
Rewrote the implementation of the scheduled repeating task, to use more performant and adequate APIs which actually wait for the scheduled work to finish, then delay the …
> Android: Fix crash in handleDroppedPeers

- example/ios/Podfile.lock
- example/ldk/index.ts
- example/tests/eclair.ts
- example/tests/unit.ts
- example/tests/utils/test-profile.ts
- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkFeeEstimator.kt
- lib/ios/Classes/LdkFeeEstimator.swift
- lib/ios/Ldk.m
- lib/ios/Ldk.swift
- lib/src/ldk.ts
- lib/src/lightning-manager.ts
- lib/src/utils/types.ts
Adds support for new fee type needed by LDK for sweeping outputs
> fix: handle output spending fee

- example/ios/Podfile.lock
- lib/package.json
- lib/src/lightning-manager.ts
Enables trace logging for the duration of `payWithTimeout` + 10 seconds. So we can get details on paths attempted:
```
2025-01-29 14:06:28 UTC TRACE (LDK): Found a path back to us from the target with 1 hops contributing up to 22000 msat: 
[
PathBuildingHop {
node_id: Some(
NodeId(0341e41583ad691951634e24dd20252d13feace9286a85d47f220dde74e7e09a15),
),
short_channel_id: Some(
13613053463560193,
),
total_fee_msat: 0,
next_hops_fee_msat: 0,
hop_use_fee_msat: 0,
total_fee_msat - (next_hops_fee_msat + hop_use_fee_msat): 0,
path_penalty_msat: 0,
path_htlc_minimum_msat: 1,
cltv_expiry_delta: 0,
},
] (lightning::routing::router 2834)
```
> feat: enable trace logs for payments

- lib/src/mock.ts
Should remove warnings in Bitkit unit tests
> chore: mock readAddressesFromFile()

- lib/android/src/main/java/com/reactnativeldk/Helpers.kt
- lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt
We're bumping react-native version for Bitkit and it now uses Kotlin v2 compiler which seems to be a bit stricter with types. This allows the values of the payments HashMap to be nullable.
> refactor(kotlin): update HashMap types to support nullable values

- lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- lib/ios/Ldk.swift
Found an occasional issue with the route finding using the local graph and a restore seems to fix it so this just resets graph and scorer automatically while attempting a payment.
- Attempts payment flow normally
- Specifically catches RouteNotFound error returned by LDK (any other error handled as before)
- For route not found error:
- Delete cached scorer
- Delete cached graph
- Download scorer and init
- Download graph and init
- Restart channel manager (to load new graph and scorer)
- Add all peers again
- Retry payment with same params
Handling this reset and retry takes an additional 10 seconds on iOS and about 30 seconds on Android (could be my device).
> Reset graph and scorer if failing to find a path
