example/App.tsx, example/android/settings.gradle, example/ios/Podfile.lock, example/package.json, example/yarn.lock, lib/android/src/main/java/com/reactnativeldk/Helpers.kt, lib/android/src/main/java/com/reactnativeldk/LdkModule.kt, lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt, lib/android/src/main/java/com/reactnativeldk/classes/LdkLogger.kt, lib/ios/Classes/LdkChannelManagerPersister.swift, lib/ios/Classes/LdkFilter.swift, lib/ios/Classes/LdkLogger.swift, lib/ios/Helpers.swift, lib/ios/Ldk.m, lib/ios/Ldk.swift, lib/src/ldk.ts, lib/src/lightning-manager.ts, lib/src/utils/types.ts
- Cooperatively close channels
- Force close channels if peer is offline by passing `force: true`
- Swift and kotlin will write all LDK logs to a file if passed through with `ldk.setLogFilePath(logPath)`
- Example app shows LDK logs in modal
Note: This PR doesn't solve #31
=> Closing channels and log files

README.md
This PR:
- Adds Android installation instructions to README.md.
=> Add Android Installation Instructions

example/ios/Podfile.lock, lib/package.json, lib/src/utils/helpers.ts
This PR:
- Updates `startParamCheck` method in `helpers.ts`.
- Bumps version to `0.0.58`.
=> Start Param Check Update

lib/src/lightning-manager.ts
This PR:
- Ensures unsubscribeFromPaymentSubscriptions is called on error in subscribeAndPay method.
=> Unsubscribe From Payments On Error

lib/src/lightning-manager.ts, lib/src/utils/types.ts
This PR:
- Saves payment ids to storage and attempts to abandon them on start.
=> Abandon Payment IDs

lib/src/lightning-manager.ts
This PR:
- Adds `rebroadcastAllKnownTransactions` method to `lightning-manager.ts`.
=> Rebroadcast Transactions

example/App.tsx, example/ios/Podfile.lock, lib/package.json, lib/src/lightning-manager.ts
This PR:
- Updates the `rebroadcastAllKnownTransactions` method.
- Makes `getLdkBroadcastedTxs` method public.
=> Rebroadcast Update

lib/src/lightning-manager.ts
This PR:
- Updates `removeLdkPaymentId` and `abandonPayment` logic.
=> Abandon Payment Update

example/ios/Podfile.lock, lib/package.json
This PR:
- Bumps version to `0.0.69` in `package.json`.
=> Version Bump

example/ios/Podfile.lock, lib/package.json
This PR:
- Bumps the version to `0.0.71` in `package.json`.
=> Bump Version to 0.0.71

example/package.json, example/yarn.lock
This PR:
- Updates `rn-electrum-client` in example project.
- Updates `yarn.lock` in example project.
=> chore(lightning): Update rn-electrum-client

example/ios/Podfile.lock, lib/ios/Ldk.swift, lib/package.json, lib/src/utils/types.ts
- Fixes LDK hanging after skipping rapid gossip sync
- Gossip level logging
- Version bump
=> Rapid gossip sync skip fix

example/ios/Podfile.lock, example/yarn.lock, lib/package.json
This PR:
- Bumps version to `0.0.74` in `package.json`.
=> Bumps Version to 0.0.74.

lib/ios/Ldk.swift
On iOS we are not able to pass our `UserConfig` where we use `set_minimum_depth(1)` to the channel manager init method when restoring a node. Only on first startup are our settings used correctly. So if a user opens up a channel on the 2nd time the wallet is started then they will have to wait 6 confs to be able to use that channel. 
This change only restores a node if there are existing channel monitors so our 1 block channel config is used at least for the user's first channel.
Will be fixed properly when [this PR](https://github.com/lightningdevkit/ldk-swift/pull/85) is in a release.
=> iOS only restore a node if existing channel monitors found

example/ios/Podfile.lock, lib/package.json
This PR:
- Bumps the version to 0.0.75 in `package.json`.
=> Bumps version to 0.0.75.

example/ios/Podfile.lock, lib/package.json
This PR:
- Bumps version to `0.0.80`.
=> Bump Version

lib/android/src/main/java/com/reactnativeldk/Helpers.kt
This PR:
- Divides msat values by `1000` prior to converting to int in `Helpers.kt`.
=> Android Helpers Calc Fix

lib/ios/Ldk.swift, lib/src/ldk.ts, lib/src/lightning-manager.ts, lib/src/utils/types.ts
- Converting sats per byte to sats per 1000 weight
- Allow passing in custom rapid gossip sync server URL
=> Fee calc fix

lib/android/src/main/java/com/reactnativeldk/Helpers.kt, lib/android/src/main/java/com/reactnativeldk/classes/LdkChannelManagerPersister.kt, lib/ios/Classes/LdkChannelManagerPersister.swift, lib/ios/Helpers.swift, lib/package.json
Temp removes caching and loading of probabilistic scorer to avoid crash
=> Remove scorer cache causing crash

example/ios/Podfile.lock, lib/package.json, lib/src/lightning-manager.ts
This PR:
- Bumps version to 0.0.88.
- Updates `res` to `r` in `payWithTimeout` method.
=> Bump version to 0.0.88

example/ios/Podfile.lock, lib/package.json, lib/src/lightning-manager.ts
Reverts change from https://github.com/synonymdev/react-native-ldk/pull/118
=> Timeout abandon payment revert

lib/android/src/main/java/com/reactnativeldk/LdkModule.kt, lib/ios/Ldk.swift, lib/package.json, lib/src/ldk.ts, lib/src/lightning-manager.ts
- Android output recovery
- Android timeout function type
- Output recovery message fix
- Version bump
=> Android output recovery

example/ios/exmpl.xcodeproj/project.pbxproj, lib/android/src/main/java/com/reactnativeldk/classes/LdkLogger.kt, lib/ios/Classes/LdkLogger.swift
closes https://github.com/synonymdev/react-native-ldk/issues/143
=> Logging time, module and line number

example/ios/Podfile.lock, lib/android/src/main/java/com/reactnativeldk/LdkModule.kt, lib/ios/Ldk.swift, lib/package.json, lib/src/lightning-manager.ts
- Skip adding peers when doing a force close without broadcasting
- Add node ID to logs
=> Recovery fix

example/docker/nginx.conf, example/tests/lnd.ts, example/tests/utils/index.ts, example/tests/utils/test-profile.ts, lib/src/lightning-manager.ts
add force-close test, but disable it for now
=> fix: increate fee for sweeping force-closed tx

backup-server/README.md, backup-server/package.json, backup-server/src/server.js, lib/package.json
Aso I've synced backup-server version with rn-ldk
=> fix: add bitkit_lightning_activity backup category

lib/android/src/main/java/com/reactnativeldk/LdkModule.kt
- Prevents reconnecting to a peer if in LDK peer list already
- Prevents connecting to peer if currently already being connected to
- Watched LDK peer list on a timer and attempts to re connect to any dropped peers every 1s
=> feat: watches for dropped peers and prevents duplicate connections on android

.github/workflows/e2e-ios.yml, .github/workflows/mocha-ios.yml
this PR fixes e2e-ios test
mocha-ios is still WIP
=> feat: run e2e-ios tests on macos-14

backup-server/src/server.js
Add a key for wallet data backup for Bitkit.
=> feat: add key for wallet data backup
